command = <mention?> <whitespace> demand (<whitespace> args)?

args = {statement <whitespace?>}

<statement> = word
          | int
          | float
          | string
          | statement-pair
          | keyword
          | demand
          | mention
          | (<"("> command <")">)

demand = <"!"> word

mention = '<@!' int '>'

statement-pair = statement ":" statement

float = (#'\d+' &#'[\s\p{S}\p{P}]|$') '.' (#'\d+' &#'[\s\p{S}\p{P}]|$')

int = #'\d+' &#'[\s\p{S}\p{P}]|$'

keyword = word '=' statement

string = <'\"'> {word | whitespace | punctuation} <'\"'>

word = #'\w+' &#'\W|$'

punctuation = #'\p{Punct}'

whitespace = #"\s+"
